# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chemical Development
email: info@chemicaldevelopment.us
description: > # this means to ignore newlines until "baseurl:"
  Math U Programming
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chemicaldevelopment.us" # the base hostname & protocol for your site
twitter_username: dev_ceb
github_username:  ChemicalDevelopment

# Build settings
markdown: kramdown
