title: ChemicalDevelopment
description: 'A real company'
author: 'Cade Brown'

github: http://github.com/ChemicalDevelopment/

permalink: /:year/:month/:day/:title.html

excerpt_separator: <!--more-->

include: [".well-known"]
keep_files: ['.well-known/acme-challenge']


