### GENERAL SETTINGS ###

# Site settings
title: ChemicalDevelopment.
description: "A Real Company"
analytics: UA-93096815-1
baseurl: "/"
url: "http://chemicaldevelopment.us"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more-->

colors:
  primary: "#93d092"
  primary_rgb: "0,179,254"
  secondary: "#6079a8"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:  
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: twitter
    url: http://twitter.com/dev_ceb

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - 401 Henley St
    - 23890, Tennessee
    - United States.
email: info@chemicaldevelopment.us
tel: +1 865-368-8485


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Cade Brown
    position: CEL
    text: Cade is the main developer, and CEL (Chief Executive Loon) of ChemicalDevelopment and its projects.
    img: cade.jpg
    social:
      - title: envelope #use for email address
        url: mailto:cade@cade.site
      - title: twitter
        url: http://twitter.com/dev_ceb
  - name: Greg Croisdale
    position: CFL
    text: Greg handles finances, dealings with the school, and more.
    img: 
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Reece Brown
    position: Community Relations Manager
    text: Reece handles educating and exciting the public about all the work we do at ChemicalDevelopment.
    img: reece.jpg
    social:
      - title: envelope #use for email address
        url: mailto:reece@chemicaldevelopment.us


# Clients information. Shown on Home and About pages.
#clients:
#  - name: dribbble
#    img: client01.png


# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "We strive to create high quality, freedom respecting software and solutions."

# Testimonial content. Shown on Home and About page.
#testimonial:
#    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
#    author: Marcel Newman
#    position: WEB DESIGNER - BLACKTIE.CO

gems:
  - jekyll-redirect-from
