brand:
  name: ChemicalDevelopment
menu-string: Menu

nav:
  - title: Home
    url: '/'
  - title: Music
    url: '/music/'
  - title: About
    url: '/about/'

copyright: Copyright &copy; ChemicalDevelopment 2018

social-buttons:
  - icon: fa fa-twitter
    url: 'http://twitter.com/dev_ceb' 
  - icon: fa fa-linkedin
    url: 'https://www.linkedin.com/in/cade-brown'
  - icon: fa fa-github
    url: 'https://github.com/ChemicalDevelopment'

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'

